### ISSUE TITLE
Error message: Incompatible with the current KeePass version

### ISSUE THREAD

**Issue by AndreKR** [Rookiestyle/KeePassOTP#31]
I just installed the plugin (by copying it into the Plugins folder). On start of KeePass I get this error message:

![image](https://user-images.githubusercontent.com/1188538/104192227-d12be900-541e-11eb-8f54-58acd9ae1613.png)

OS: Windows 7
KeePass Version: 2.47 (64-bit)
Plugin Version: v0.23

**Comment by Rookiestyle** [comment]
I suppose something as mentioned in issue #24 

Can you please try the same?
If not working, please let me know your .NET version

**Comment by AndreKR** [comment]
I have .NET Framework 4.8 installed, I'm gonna check if I can install 4.5.1 in addition to that.

**Comment by AndreKR** [comment]
It says
> .NET Framework 4.5.1 or a later update is already installed on this computer.

So I guess that means 4.8 includes everything from 4.5.1 as well.

**Comment by Rookiestyle** [comment]
I'll try to set up a vm and check more in detail

**Comment by AndreKR** [comment]
Let me know if I can help. I'm not really a .NET developer, but I happen to have Visual Studio 2019 installed and I have checked out the code and opened the .sln file.

Don't really know how to run or debug or check for missing dependencies from here.

Have you seen [this](https://stackoverflow.com/questions/3927194/getting-strange-system-drawing-bitmap-cannot-be-located-error)?

**Comment by AndreKR** [comment]
I fiddled around a bit more, I extracted the KeePass source to `..\_KeePass_Source`, removed the `sgen` line from "Build Events" (because it failed) and ran a ReleasePlgx build and guess what, I have a `KeePassOTP.plgx` that works with the `KeePass.exe` that was also created. With the original `KeePass.exe` I get the same error as shown above.

**Comment by Rookiestyle** [comment]
Thanks for your additional input!
Unfortunately I'm still not able to able to reproduce this (having issues with my Win 7 vm)

Can you meanwhile please try the attached version?
[KeePassOTP.zip](https://github.com/Rookiestyle/KeePassOTP/files/5801091/KeePassOTP.zip)

**Comment by AndreKR** [comment]
Same issue.

![image](https://user-images.githubusercontent.com/1188538/104297014-a3987b80-54c2-11eb-96e6-e9f569b35047.png)

**Comment by Rookiestyle** [comment]
OK, I'm running out of ideas since in my VM with Windows 7, there is no issue:
Windows 7 - WIndows NT 6.1.7601 Service Pack 1
KeePass 2.47 (64 bit)
[KeePassOTP.zip](https://github.com/Rookiestyle/KeePassOTP/files/5803196/KeePassOTP.zip)


Can you please try once again with the attached version.
If the issue is not solved by this version:
- Does the error message relate to Version 2.0.0.0 or to Version 4.0.0.0?
- Does file Sytem.drawing.dll exist in folder c:\windows\assembly? which version?
- Did you  try a repair of your dotnet installation - https://www.microsoft.com/download/details.aspx?id=30135

**Comment by AndreKR** [comment]
With this version I'm getting:

![image](https://user-images.githubusercontent.com/1188538/104342320-fdb53300-54fa-11eb-9471-1acc3c1eafdb.png)

The error message only mentions version 4.0.0.0 (see screenshot above). With the version in your first ZIP the error message is the same.

In `c:\windows\assembly` I have "Libraries" and there is one called "System.Drawing". It's version 2.0.0.0:

![image](https://user-images.githubusercontent.com/1188538/104342708-66041480-54fb-11eb-9bb2-83006667f430.png)

I'll run the repair now.

**Comment by Rookiestyle** [comment]
Ok, at least there is some progress...

Please start KeePass with the `-debug` Switch using the commandline or [Win]-[R]
KeePass will save a log file containing some more details and this hopefully helps me identifying this new issue

**Comment by AndreKR** [comment]
Here's the log for the latest zip: [tmp9607.txt](https://github.com/Rookiestyle/KeePassOTP/files/5807276/tmp9607.txt)

I tried the plgx from the previous zip as well and I still get the error but it does not create a debug log, even with a cleared plugin cache. I guess the `--debug` is only for compilation errors, not for runtime errors or something?

**Comment by Rookiestyle** [comment]
Error message `The type or namespace name 'Tasks' does not exist in the namespace 'System.Threading' (are you missing an assembly reference?)` is correct for .Net framework 3.5 since this was introduced with 4.0.

A plgx file essentially contains the entire sourcecode of the plugin and KeePass is using the .NET framework built-in compilers to actually compile it.
When doing this, KeePass uses these CompilerVersion:
* null (2.0)
* v3.5
* v4
* v4.0
* v4.0.30319
* v4.5

In your case either only 'null' (v2.0) and 'v3.5' are used by KeePass itself or the other compilers do not even return an error message.
Either way, I have no idea what is happening

Nevertheless, please use the attached version, it does not use System.Threading.Tasks and hopefully this one is working.
If not, there's nothing more that I can do.
[KeePassOTP.zip](https://github.com/Rookiestyle/KeePassOTP/files/5807869/KeePassOTP.zip)

**Comment by Rookiestyle** [comment]
Closing this as there is no negative feedback.

The meanwhile released version [v0.24](/Rookiestyle/KeePassOTP/releases/v0.24) contains the changes done in this issue

**Comment by AndreKR** [comment]
In case anyone has a similar issue... I got the same error ("is not compatible", but with different details) with KeePassOTP 1.4 and KeePass 2.47. However, after upgrading KeePass itself to 2.51.1, the error went away.
